source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'CirrenaFramework_Example', :exclusive => true do
  pod "CirrenaFramework", :path => "../"
end

target 'CirrenaFramework_Tests', :exclusive => true do
  pod "CirrenaFramework", :path => "../"

  pod 'FBSnapshotTestCase'
end
